version: "3"

services:
  oprish:
    container_name: oprish
    env_file: .env
    restart: unless-stopped

    environment:
      - BROKERS=kafka

    ports:
      - "8000:8000"

    command: ["bash", "-c", "sleep 10 && /bin/oprish"]

    build:
      context: ./oprish
      dockerfile: Dockerfile

  pandemonium:
    container_name: pandemonium
    env_file: .env
    restart: unless-stopped

    environment:
      - BROKERS=kafka

    ports:
      - "9000:9000"

    command: ["bash", "-c", "sleep 10 && /bin/pandemonium"]

    build:
      context: ./pandemonium
      dockerfile: Dockerfile

  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      - KAFKA_BROKER_ID=0
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_NUM_PARTITIONS=3
      - CONFLUENT_SUPPORT_METRICS_ENABLE=0
    ports:
      - "9092:9092"
    links:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    ports:
      - "2181:2181"
