version: "3"

x-pull-policy:
  &pull-policy
  pull_policy: always

services:
  oprish:
    <<: *pull-policy
    image: ghcr.io/eludris/oprish:next
    ports:
      - ${OPRISH_PORT:-7159}:7159

  pandemonium:
    <<: *pull-policy
    image: ghcr.io/eludris/pandemonium:next
    ports:
      - ${PANDEMONIUM_PORT:-7160}:7160

  effis:
    <<: *pull-policy
    image: ghcr.io/eludris/effis:next
    ports:
      - ${EFFIS_PORT:-7161}:7161
