version: "3"

services:
  oprish:
    container_name: oprish
    env_file: .env
    restart: unless-stopped

    environment:
      BROKERS: kafka
      # God have mercy
      ROCKET_DATABASES: "{redis-cache={url=\"redis://keydb\"}}"
      DB_URL: "mysql://root:root@mariadb/eludris"

    ports:
      - "7159:7159"

    build:
      context: ./oprish
      dockerfile: Dockerfile

  pandemonium:
    container_name: pandemonium
    env_file: .env
    restart: unless-stopped

    environment:
      BROKERS: kafka
      # Now for redis url
      REDIS_URL: redis://keydb # Syke
      DB_URL: "mysql://root:root@mariadb/eludris"

    ports:
      - "7160:7160"

    build:
      context: ./pandemonium
      dockerfile: Dockerfile

  keydb:
    image: eqalpha/keydb
    restart: unless-stopped

  mariadb:
      image: mariadb:latest

      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_ROOT_HOST=%
        - MYSQL_DATABASE=eludris
