# Make sure to copy this file into `Eludris.toml`

# You can uncomment the sections that you want and change their config values,
# this is just the defaults.

instance_name = "" # This is required, has to be over 0 characters long.

# Optional instance description, can be from 1 to 2048 characters long.
#description = ""

# With rate limits, reset_after is the number of seconds between every bucket reset.

[oprish]
url = "" # This instance's Oprish url
#message_limit = 2048 # The maximum message content length.
#bio_limit = 250 # The maximum bio length

#[oprish.rate_limits]
# Reference todel/src/conf/oprish.rs

[pandemonium]
url = "" # This instance's Pandemonium url
#rate_limit = { reset_after = 5, limit = 10 }

[effis]
url = "" # This instance's Effis url
#file_size = "20MB" # The maximum file size for all the assets
#attachment_file_size = "100MB" # The maximum file size for the attachment bucket
#proxy_file_size = "50MB" # The maximum file size for a proxied file

# Effis rate limits are special, you're not only limited by how many requests per
# bucket reset, but also by how big the files you upload are, so assuming a rate limit
# with a limit of 5 and a file_size_limit of 10MB, I can either upload 1 10MB file
# (if the effis.file_size allows so) or for example 5 2MB files, after either of
# which I get rate limited.

#[effis.rate_limits]
# The rate limit for all buckets besides the attachments one, these buckets are
# stuff like avatars, guild icons, etc.
#assets = { reset_after = 30, limit = 5, file_size_limit = "30MB" }
#attachments = { reset_after = 120, limit = 40, file_size_limit = "500MB" }
# These are normal rate limits
#fetch_file = { reset_after = 120, limit = 40 }
#proxy_file = { reset_after = 120, limit = 40 }

# This entire section *is* optional and Eludris *will* function without it. However,
# using an SMTP relay for your instance is really beneficial as - not only does it
# ensure that every user has a valid email **that they own, and not just some other
# person's** - it also makes stuff like password resets possible.
[email]
# The URL of your SMTP relay
relay = ""
# The name of your instance's sender
name = ""
# The address of your instance's sender
address = ""
# The credentials of your SMTP relay
#credentials = { username = "", password = "" }

# The subjects of the emails your instance sends out if you have an SMTP relay setup.
# Leaving a subject as an empty string makes the email have no subject.
#[email.subjects]
# The subject of your instance's verification email
#verify = "Verify your Eludris account"
#delete = "Your Eludris account has been successfully deleted"
#password_reset = "Your Eludris password has been reset"
#user_updated = "Your Eludris account has been updated"
