[build]
rustflags = [
  "-A", "clippy::uninlined_format_args", # Consistency since you cannot inline "complex" args such as `self.foo`
  "-A", "clippy::too_many_arguments",
  "-A", "clippy::blocks_in_conditions" # TODO: remove this when they fix the lint
]
